version: '3.8'
services:
  kameleoon:
    image: ecyas/kameleoon-trial-task:1.0.0-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:kameleoon
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      - SERVER_PORT=8081
